name: BigBrother
version: 1.5.0-beta
api: [3.0.0]
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
author: shoghicp
website: https://github.com/shoghicp/BigBrother
load: STARTUP
main: shoghicp\BigBrother\BigBrother
softdepend:
 - SimpleAuth
